[package]
name = "source_defs_3l14"
description = "Design time structures for 3L14"
workspace = "../../.."
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
asset_3l14.workspace = true
math_3l14.workspace = true
nab_3l14.workspace = true
world_3l14.workspace = true
proc_macros_3l14.workspace = true

glam.workspace = true
serde.workspace = true