use crate::{debug_label, Renderer};
use asset_3l14::{AssetLifecycler, AssetLoadRequest};
use bitcode::{Decode, Encode};
use debug_3l14::debug_gui::DebugGui;
use egui::Ui;
use proc_macros_3l14::Asset;
use std::sync::Arc;
use wgpu::{Buffer, BufferUsages};
use wgpu::util::{BufferInitDescriptor, DeviceExt};
use crate::assets::GeometryFile;
