[package]
name = "proc_macros_3l14"
workspace = "../.."
edition.workspace = true

[lib]
name = "proc_macros_3l14"
path = "proc_macros.rs"
proc-macro = true

[dependencies]
syn = { version =  "3.0.3", features = ["extra-traits"] } # TODO: switch to unsynn? ; extra-traits only for debugging
quote = "1.0.47"
proc-macro2 = "1.0.107"
metrohash.workspace = true