[package]
name = "proc_macros_3l14"
version = "0.1.0"
edition = "2021"

[lib]
name = "proc_macros_3l14"
path = "proc_macros.rs"
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
metrohash = "1.0.6"