[package]
name = "containers_3l14"
description = "Various container types"
workspace = "../../.."
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
math_3l14.workspace = true # needed by R* Trees, move that elsewhere?

crossbeam.workspace = true