name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup SDL
      # You may pin to the exact commit or the version.
      # uses: libsdl-org/setup-sdl@c3f966b577bda4aa30a21fab1875fc89f0151a6b
      uses: libsdl-org/setup-sdl@v1
      with:
        # Required version of SDL (2.x.y, 2-any, 2-latest, 2-head, 3-head), or git hash
        version: 2-latest # default is 2-any
        # Version of SDL_image (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
        # version-sdl-image: # optional
        # Version of SDL_mixer (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
        # version-sdl-mixer: # optional
        # Version of SDL_net (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
        # version-sdl-net: # optional
        # Version of SDL_rtf (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
        # version-sdl-rtf: # optional
        # Version of SDL_ttf (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
        version-sdl-ttf: 2-any # optional
        # Allow pre-releases
        pre-release: false # default is true
        # CMake build type (Release/Debug/RelWithDebInfo/MinSizeRel)
        build-type: Release # default is Debug
        # Build and install SDL_test library
        # sdl-test: # optional, default is false
        # Path of a CMake toolchain file
        # cmake-toolchain-file: # optional
        # CMake generator name (see https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html)
        # cmake-generator: # optional
        # Extra CMake arguments during configuration
        # cmake-arguments: # optional
        # Install dependencies (supports apt-get, dnf, brew, and msys2-pacman)
        # install-linux-dependencies: # optional
        # Run commands as `$shell $file` (with $file containing the build commands)
        # shell: # optional
        # Unique string to include in the GitHub SDL cache hash
        # discriminator: # optional
        # Add path of the SDL (shared) library to PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH
        # add-to-environment: # optional, default is false
        # A GitHub API token.
        # token: # optional, default is ${{ github.token }}
    
    - name: Build
      run: cargo build --verbose --release
